### ISSUE TITLE
以管理员安装后，打开报错

### ISSUE THREAD

**Issue by keepfighting666** [ZGHHGZ/ESIS#1]
![image](https://github.com/ZGHHGZ/ESIS/assets/86222061/96de8424-186d-4d87-98ac-b274ac7e5e69)
打开软件就是这样，win11系统，安装的最新的版本

**Comment by ZGHHGZ** [comment]
软件可能会出现被防火墙或杀毒软件错误识别为风险文件，而导致安装不完整，可关闭防火墙及杀毒软件再重新安装；或者进入下方群聊下载安装后的解压文件并手动替换安装路径下的同名文件。
![image](https://github.com/ZGHHGZ/ESIS/assets/88225620/16c18dfa-ba50-4bcd-a784-7be5eb6c5e27)
![image](https://github.com/ZGHHGZ/ESIS/assets/88225620/fccf5db2-e406-4a2b-8ac6-161d3be44eca)
